FROM scratch
ADD docker/al2023.tar.xz /
CMD ["/bin/bash"]

#RUN dnf update -y
#RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.rpm.sh' | bash
#RUN dnf install -y composer php php-intl php-mysqlnd symfony-cli
#ADD docker/httpd.conf /etc/httpd/conf/httpd.conf
